export const facilityFeatureLabels: { [key: string]: string } = {
  pool: "プール",
  sauna: "サウナ",
  parking: "駐車場",
  gym: "ジム",
  basketball: "バスケットボール",
  badminton: "バドミントン",
  volleyball: "バレーボール",
  shower: "シャワー",
  yoga_room: "ヨガルーム",
  studio: "スタジオ",
  cafe: "カフェ",
  wheelchair_accessible: "バリアフリー",
  conference_room: "会議室",
  locker_room: "ロッカールーム",
  personal_training: "パーソナルトレーニング",
  group_classes: "グループクラス",
  kids_area: "キッズエリア",
  massage: "マッサージ",
  spa: "スパ",
  tennis: "テニス",
  rock_climbing: "ボルダリング",
  martial_arts: "格闘技",
  dance_studio: "ダンススタジオ",
  outdoor_area: "屋外エリア",
  free_weights: "フリーウェイト",
  cardio_machines: "有酸素マシン",
  stretching_area: "ストレッチエリア",
};

export type FacilityFeature = keyof typeof facilityFeatureLabels;